Add i18n support (wip)
eventzimmer/site pull request #29
Opened 2019-10-01 00:09 UTC by m1ga

Hi :wave: 
found your project in the Hacktoberfest section! Started to add i18n support (https://github.com/eventzimmer/site/issues/19) using vue-i18n.
It will add a select box with de/en and will change the strings on the fly.

It is my first time using Vue so I'm still learning to get my way around the project :smile: But it is working already but can still be optimized!

PS:
Hoffentlich nicht allzu schlimm, ich passe noch einiges an :wink:

2019-10-02 13:44 UTC, Fohlen commented
Hey @m1ga thanks for tackling this PR! ✨ 

Apparently I hadn't watched this repo (which I thought was the default setting for repo owners) 🦆 
I will check this PR and let you know what I think and/or how it could be improved!

2019-10-02 13:46 UTC, m1ga commented
@Fohlen Nice! I still want to change the imprint/privacy part (loading custom files in custom languages).

2019-10-02 13:54 UTC, Fohlen commented
My first impression of this PR is quite good, here are my two cents:

- you can use the `store` to save the language setting. The state of the store is automatically persisted to `localStorage` and restored upon loading, thus no need for `vue-cookies`. Just use `store.state.lang` once loaded.
- we could use [vue-router](https://router.vuejs.org/) to assemble the different parts (impress / privacy pages). I am unsure if it is worth the effort. What do you think? 
- the language button should be where the other buttons are. I can handle the CSS as you like

I do really like your translations, head's up 👍 
Greetings from rainy Tuebingen! 🌧

2019-10-03 15:00 UTC, Fohlen requested changes
Looks almost good to go. What's your decision about the `imprint` / `privacy` pages? Should we just create different links in the footer or should we use `vue-router` ?

2019-10-03 15:00 UTC, Fohlen commented on src/store.js
> +    },
Unless we're planning to return a different result for `lang` we don't really need a getter, we can use `store.state.lang`.

2019-10-03 15:07 UTC, m1ga commented
> Looks almost good to go. What's your decision about the `imprint` / `privacy` pages? Should we just create different links in the footer or should we use `vue-router` ?

I'll have to have a closer look what vue-route does and how it works. Different links would be quicker and if it is only de/en it should be fine.

BTW:
I've moved the Select-Box to the right and applied the normal style. I'm not sure if they should look like this at all:
![Screenshot_20191003_170256](https://user-images.githubusercontent.com/4334997/66139148-33812180-e600-11e9-9a01-a4fac44ce62c.png)
or if my Firefox/Fedora 30 is breaking the style :smile: So I think you can style it better later on (e.g. make it smaller?)

2019-10-03 15:24 UTC, Fohlen commented
> > Looks almost good to go. What's your decision about the `imprint` / `privacy` pages? Should we just create different links in the footer or should we use `vue-router` ?
> 
> I'll have to have a closer look what vue-route does and how it works. Different links would be quicker and if it is only de/en it should be fine.
> 
> BTW:
> I've moved the Select-Box to the right and applied the normal style. I'm not sure if they should look like this at all:
> ![Screenshot_20191003_170256](https://user-images.githubusercontent.com/4334997/66139148-33812180-e600-11e9-9a01-a4fac44ce62c.png)
> or if my Firefox/Fedora 30 is breaking the style 😄 So I think you can style it better later on (e.g. make it smaller?)

I believe this is expected behaviour, but I can make some amendments to make it more compelling.
Let's do it like this:

- I'll sweep over your PR and add some finishing touches here and there
- You'll add links to the english imprint / privacy (just copy the german one)
- I'll translate the rest of the imprint and privacy, as I have time
- Once done, I merge the PR

2019-10-03 15:25 UTC, m1ga commented
sounds like a good plan! I'll have a look at it tomorrow.

2019-10-03 21:27 UTC, Fohlen commented
Closing in favour of #31

2019-10-03 21:27 UTC, closed without merging