added default language for navigator.language
eventzimmer/site pull request #37
Opened 2019-10-09 14:48 UTC by VivekSingh777

Submitting a pull request
-------------------------

First of all, thank you for taking the time to contribute to this project :sparkles:!
Every contribution means a lot to us. This is an open source effort, heck yeah.

Before you submit your pull request please read [our contribution guideline](https://github.com/eventzimmer/schema/blob/master/CONTRIBUTING.md).
It includes a `checklist` for the most common questions.

2019-10-09 14:50 UTC, VivekSingh777 commented
@Fohlen Done

2019-10-09 21:30 UTC, Fohlen requested changes

2019-10-09 21:30 UTC, Fohlen commented on src/store.js
> +console.log(navigator.language);
The `console.log` statement shouldn't be here?

2019-10-09 21:30 UTC, Fohlen commented on src/store.js
> +    language: navigator.language.substring(0, 2) || 'de'
This doesn't really check if the language has previously been set? 

It should be `null` I believe, and in the `main.js` we should check if it is `null`, and if it is, set the `navigator.language` setting!

2019-10-10 06:43 UTC, VivekSingh777 commented on src/store.js
> +    language: navigator.language.substring(0, 2) || 'de'
let me check on that

2019-10-11 10:45 UTC, Fohlen commented on src/store.js
> +    language: navigator.language.substring(0, 2) || 'de'
If you need more help on the matter, let me know, I'd be happy to finish this PR 💨

2019-10-12 08:14 UTC, VivekSingh777 commented on src/store.js
> +    language: navigator.language.substring(0, 2) || 'de'
@Fohlen Looking into the same

2019-10-12 08:28 UTC, VivekSingh777 commented
@Fohlen Update the code now. Please review

2019-10-12 08:50 UTC, Fohlen commented
This looks good, I'll be merging asap! You may add yourself to the [list of contributors](https://github.com/eventzimmer/schema/blob/master/CONTRIBUTORS.md) as you like!

2019-10-13 00:40 UTC, merged