Redesign event cards
eventzimmer/site pull request #48
Opened 2019-10-19 22:42 UTC by Sbaah

Submitting a pull request
-------------------------

First of all, thank you for taking the time to contribute to this project :sparkles:!
Every contribution means a lot to us.

Please make sure you check everything on this list:

- add your change to the `CHANGELOG.md` in the respective repository
- make sure tests pass :white_check_mark:
- if your commit does close an existing ticket: use a [closing issue keyword](https://help.github.com/en/articles/closing-issues-using-keywords) (e.g: `closes #15`) in your commit. This makes live easier for our issue tracker.
- if possible, test your changes with the deploy preview at least once. Promises made, you will enjoy it :hamburger: 
- add yourself to the [`CONTRIBUTORS.md`](https://github.com/eventzimmer/.github/blob/master/CONTRIBUTORS.md) as you like

2019-10-20 11:06 UTC, Fohlen commented
Hey @Sbaah I will look at your proposal and let you know what I think!

2019-10-20 11:07 UTC, Fohlen requested changes

2019-10-20 11:07 UTC, Fohlen commented on CHANGELOG.md
> +### Added
This should be added unter the `Unreleased` version as it has been not yet released. Can you change this?

2019-10-20 16:43 UTC, Sbaah commented on CHANGELOG.md
> +### Added
Done.

2019-10-21 07:16 UTC, Fohlen commented
Hey, I am superseding your work with #51 
Do you think this is ok? How do you like the new display?

2019-10-21 15:41 UTC, closed without merging